### ISSUE TITLE
A network service error has occurred on password change

### ISSUE THREAD

**Issue by ghost** [vnc-biz/vnc-ad-password-change#2]
Hello All,

Running 8.6.0 without patches and installed ad-password using zmpkg, my Zimbra server is on
myzimbra.com and I log on using domain barrydegraaff.tk with ldap and SSL.

I did all the steps from the readme, double cheched rebooted:
https://github.com/Zimbra-Community/vnc-ad-password-change/blob/master/README.md

mailbox.log shows:

2016-03-31 08:21:48,426 INFO  [qtp509886383-458:http://127.0.0.1:8080/service/soap/ChangePasswordRequest] [ip=127.0.0.1;ua=zclient/8.6.0_GA_1153;] soap - ChangePasswordRequest elapsed=108
2016-03-31 08:21:48,427 WARN  [qtp509886383-459:https://192.168.1.26:8443/h/changepass?skin=harmony] [] webclient - system failure: java.lang.NullPointerException
com.zimbra.common.soap.SoapFaultException: system failure: java.lang.NullPointerException
ExceptionId:qtp509886383-458:http://127.0.0.1:8080/service/soap/ChangePasswordRequest:1459405308426:8483857bfbe60d9a
Code:service.FAILURE
    at com.zimbra.common.soap.Soap12Protocol.soapFault(Soap12Protocol.java:90)
    at com.zimbra.common.soap.SoapTransport.extractBodyElement(SoapTransport.java:355)
    at com.zimbra.common.soap.SoapTransport.parseSoapResponse(SoapTransport.java:328)
    at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:261)
    at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:170)
    at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:408)
    at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:721)
    at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:715)
    at com.zimbra.client.ZMailbox.invokeJaxb(ZMailbox.java:703)
    at com.zimbra.client.ZMailbox.changePassword(ZMailbox.java:598)
    at com.zimbra.client.ZMailbox.changePassword(ZMailbox.java:483)
    at com.zimbra.cs.taglib.tag.ChangePasswordTag.doTag(ChangePasswordTag.java:61)
    at org.apache.jsp.h.changepass._jspx_meth_zm_changePassword_0(org.apache.jsp.h.changepass:611)
    at org.apache.jsp.h.changepass._jspx_meth_c_catch_0(org.apache.jsp.h.changepass:574)
    at org.apache.jsp.h.changepass.access$13(org.apache.jsp.h.changepass:560)
    at org.apache.jsp.h.changepass$changepassHelper.invoke0(org.apache.jsp.h.changepass:1242)
    at org.apache.jsp.h.changepass$changepassHelper.invoke(org.apache.jsp.h.changepass:1321)
    at org.apache.jsp.tag.web.infra.handleError_tag._jspx_meth_c_catch_0(org.apache.jsp.tag.web.infra.handleError_tag:228)
    at org.apache.jsp.tag.web.infra.handleError_tag.doTag(org.apache.jsp.tag.web.infra.handleError_tag:92)
    at org.apache.jsp.h.changepass._jspService(org.apache.jsp.h.changepass:126)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at com.zimbra.webClient.servlet.JspServlet.service(JspServlet.java:58)
    at org.eclipse.jetty.servlet.JspPropertyGroupServlet.service(JspPropertyGroupServlet.java:139)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
    at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at com.zimbra.webClient.filters.RestFilter.doFilter(RestFilter.java:46)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at com.zimbra.webClient.filters.ForwardFilter.doFilter(ForwardFilter.java:88)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
    at com.zimbra.webClient.filters.SetHeaderFilter.doFilter(SetHeaderFilter.java:248)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:351)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:457)
    at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:326)
    at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:299)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at com.zimbra.webClient.filters.CharEncodingFilter.doFilter(CharEncodingFilter.java:37)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:544)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
    at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:462)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
    at java.lang.Thread.run(Thread.java:745)

What am I missing here?

**Comment by ghost** [comment]
Redid all the install steps from the readme with screen shared with Patrick, it does not look like a PEBKAC.... I will verify if my AD allows the password change over LDIF, but right now, I think the extension is not making a request to the AD server (digging thru logs)

**Comment by ghost** [comment]
I verified my Active Directory allows the user to change his password via PHP, so it is NOT a windows issue anymore
https://gist.github.com/barrydegraaff/7d104034140592aaaab302399a8593d3

**Comment by ghost** [comment]
Also the port number to do this is 636 
636 is a port that is allowed for both AUTH and changing password, the Zimbra default port 3269 is not allowed to change passwords on:
00002035: LdapErr: DSID-0C090C80, comment: Operation not allowed through GC port, data 0, v2580

**Comment by ghost** [comment]
Logging on the ad side:
https://gist.github.com/barrydegraaff/5224630fca0c41222429bedc2c80f280

**Comment by ghost** [comment]
Fixed in https://github.com/vnc-biz/vnc-ad-password-change/pull/4

I still cannot change my password with vnc-ad-password-change, but I am fine as the work on finding out the missing parts in the documentation allow me to use the original work at https://github.com/Zimbra-Community/ADPassword
